export const REMOVE_SIGNUP_SUCCESS = 'REMOVE_SIGNUP_SUCCESS';
export const REMOVE_SIGNUP_FAIL = 'REMOVE_SIGNUP_FAIL';
export const REMOVE_SIGNIN_SUCCESS = 'REMOVE_SIGNIN_SUCCESS';
export const REMOVE_SIGNIN_FAIL = 'REMOVE_SIGNIN_FAIL';

export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';
export const SIGNIN_USER_START = 'SIGNIN_USER_START';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAIL = 'SIGNUP_USER_FAIL';

export const POST_CREATE_SUCCESS= 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';

export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";


export const LOGOUT = 'LOGOUT';
export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';
export const REDIRECT_URL = 'REDIRECT_URL';